name: rahma_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.7
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_local_notifications: ^19.5.0
  flutter_localization: ^0.3.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.2.4
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.8.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get_it: ^7.6.4
  go_router: ^17.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  skeletonizer: ^2.1.1
  workmanager: ^0.9.0+3
  logger: ^2.5.0

dev_dependencies:
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.3
  build_runner: null
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: null

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/json/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 800
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 800

flutter_intl:
  enabled: true

  flutter_assets: null
  assets_path:
    - assets/svgs
    - assets/images
  output_path: lib/core/constants/
  filename: assets.dart
